fix @jwt and @jwtClaim entries in the directives overview table
neo4j/docs-graphql pull request #150
Opened 2024-05-15 11:53 UTC by rsill-neo4j

2024-05-15 11:54 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-150.surge.sh

Updated pages:
- [Directives](https://neo4j-docs-graphql-150.surge.sh/graphql/5/type-definitions/directives)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-05-15 11:58 UTC, lidiazuin approved these changes
LGTM!

2024-05-27 13:53 UTC, rsill-neo4j commented on modules/ROOT/pages/type-definitions/directives/index.adoc
> +| Configure the JWT authentication filter to include an additional nested JWT claim.
```suggestion
| Use in combination with `@jwt`. Configure the JWT authentication filter to include an additional nested JWT claim.
```

2024-05-27 13:54 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-150.surge.sh

Updated pages:
- [Directives](https://neo4j-docs-graphql-150.surge.sh/graphql/5/type-definitions/directives)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-05-28 14:06 UTC, darrellwarde requested changes
This looks good, I've just made some suggestions to maybe slightly improve the wording here. 🙂

2024-05-28 14:06 UTC, darrellwarde commented on modules/ROOT/pages/type-definitions/directives/index.adoc
> +| Configure the JWT authentication filter to include an additional JWT claim.
```suggestion
| Configure the JWT authentication and authorization filters to include additional JWT claims.
```

2024-05-28 14:06 UTC, darrellwarde commented on modules/ROOT/pages/type-definitions/directives/index.adoc
> +| Use in combination with `@jwt`. Configure the JWT authentication filter to include an additional nested JWT claim.
```suggestion
| Use in combination with `@jwt`. Configure the JWT authentication and authorization filters to include an additional JWT claim which is either nested or using special characters not supported by GraphQL.
```

2024-05-31 07:32 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-150.surge.sh

Updated pages:
- [Directives](https://neo4j-docs-graphql-150.surge.sh/graphql/5/type-definitions/directives)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-05-31 07:50 UTC, rsill-neo4j commented on modules/ROOT/pages/type-definitions/directives/index.adoc
> +| Use in combination with `@jwt`. Configure the JWT authentication and authorization filters to include an additional JWT claim which is either nested or using special characters not supported by Gra
```suggestion
| Used in combination with `@jwt`. Configures the JWT authentication and authorization filters to include an additional JWT claim which is either nested or using special characters not supported by GraphQL.
```

2024-05-31 07:50 UTC, rsill-neo4j commented on modules/ROOT/pages/type-definitions/directives/index.adoc
> +| Configure the JWT authentication and authorization filters to include additional JWT claims.
```suggestion
| Configures the JWT authentication and authorization filters to include additional JWT claims.
```

2024-05-31 07:52 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-150.surge.sh

Updated pages:
- [Directives](https://neo4j-docs-graphql-150.surge.sh/graphql/5/type-definitions/directives)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-04 08:28 UTC, closed without merging

2024-06-04 08:28 UTC, rsill-neo4j commented
the changes suggested are incorporated in this PR: https://github.com/neo4j/docs-graphql/pull/140