fix subscription docs
neo4j/docs-graphql pull request #154
Opened 2024-06-05 10:58 UTC by rsill-neo4j

2024-06-05 10:59 UTC, rsill-neo4j commented
should this also be fixed for older versions?

2024-06-05 11:00 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-154.surge.sh

Updated pages:
- [Type configuration](https://neo4j-docs-graphql-154.surge.sh/graphql/5/directives/schema-configuration/type-configuration)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-05 11:01 UTC, mjfwebb commented
> should this also be fixed for older versions?

That would be great if possible

2024-06-05 12:39 UTC, darrellwarde requested changes, later dismissed
It looks good, actually an additional change needed though!

2024-06-05 12:39 UTC, darrellwarde commented on modules/ROOT/pages/directives/schema-configuration/type-configuration.adoc
> +directive @subscription(events: [SubscriptionFields!]! = [CREATE, UPDATE, DELETE, CREATE_RELATIONSHIP, DELETE_RELATIONSHIP]) on OBJECT | SCHEMA
I just checked and it's actually like this, who would have known... 🥲 

```suggestion
directive @subscription(events: [SubscriptionFields!]! = [CREATED, UPDATED, DELETED, RELATIONSHIP_CREATED, RELATIONSHIP_DELETED]) on OBJECT | SCHEMA
```

2024-06-05 12:39 UTC, darrellwarde commented
> > should this also be fixed for older versions?
> 
> That would be great if possible

I don't know exactly when we made this change though.

2024-06-05 12:40 UTC, darrellwarde commented
I just checked - it was changed in version 4, so those docs can also be updated!

2024-06-05 13:33 UTC, rsill-neo4j commented on modules/ROOT/pages/directives/schema-configuration/type-configuration.adoc
> +type Movie @subscription(events: [CREATE]) {
```suggestion
type Movie @subscription(events: [CREATED]) { 
```

2024-06-05 13:34 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-154.surge.sh

Updated pages:
- [Type configuration](https://neo4j-docs-graphql-154.surge.sh/graphql/5/directives/schema-configuration/type-configuration)
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-06-10 07:11 UTC, mjfwebb approved these changes

2024-06-10 07:41 UTC, merged

2024-06-10 07:48 UTC, rsill-neo4j commented
also applied this to 6.x and 4.x