prepare 6.x for docs release
neo4j/docs-graphql pull request #213
Opened 2024-10-28 14:59 UTC by rsill-neo4j

2024-10-28 15:00 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-213.surge.sh
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-10-28 17:01 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-213.surge.sh
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-10-29 10:38 UTC, lidiazuin commented on modules/ROOT/partials/notes.adoc
> +You are looking at version 6 of the GraphQL Library.
```suggestion
This is the documentation of the GraphQL Library version 6.
```

2024-10-29 10:52 UTC, recrwplay requested changes

2024-10-29 10:52 UTC, recrwplay commented on preview.yml
> +    page-add-notes-tags: note
```suggestion
    page-add-notes-tags: note
    neo4j-base-uri: https://neo4j.com
    neo4j-docs-base-uri: https://neo4j.com/docs
```

A suggestion for using links to other docs pages - we use these attributes in preview playbooks so we can  use the form `link:{neo4j-docs-base-uri}/...` in asciidoc and the URLs will resolve as they do in publish.yml playbooks.

2024-10-29 10:52 UTC, recrwplay commented on antora.yml
> +page-add-notes-tags: note
```suggestion
asciidoc:
  attributes:
    page-add-notes-module: ROOT
    page-add-notes-tags: note
```

2024-10-29 10:52 UTC, recrwplay commented on modules/ROOT/partials/notes.adoc
> +For the long-term support (LTS) version 5, refer to link:https://neo4j.com/docs/graphql/5/[GraphQL Library version 5 LTS].
```suggestion
For the long-term support (LTS) version 5, refer to link:{neo4j-docs-base-uri}/graphql/5/[GraphQL Library version 5 LTS].
```

2024-10-29 10:52 UTC, recrwplay commented on publish.yml
Add `  - "@neo4j-antora/antora-add-notes"` to the asciidoc extensions

2024-10-29 10:57 UTC, lidiazuin commented on preview.yml
> +    page-add-notes-tags: note
If I may add to the suggestion, I would say using {docs-home} instead of {neo4j-docs-base-uri} can be more practical

2024-10-29 14:08 UTC, recrwplay commented on preview.yml
> +    page-add-notes-tags: note
That is certainly shorter. We do use `{neo4j-docs-base-uri}/` in most repos, and it's the name provided by docs-template. But I'm not going to force absolute consistency here.

2024-10-29 14:09 UTC, recrwplay commented on preview.yml
> +    page-add-notes-tags: note
If `{docs-home}` then also probably `{neo4j-home}` instead of `{neo4j-base-uri}`

2024-10-29 14:24 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-213.surge.sh
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-10-29 14:26 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-213.surge.sh
<!-- Sticky Pull Request Commentdocs-pr-changes -->

2024-10-30 11:03 UTC, lidiazuin approved these changes

2024-10-31 11:31 UTC, merged

2024-10-31 11:31 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates
View the updated docs at https://neo4j-docs-graphql-213.surge.sh
<!-- Sticky Pull Request Commentdocs-pr-changes -->