Adds a more step by step guide to Federation
neo4j/docs-graphql pull request #9
Opened 2023-08-04 12:36 UTC by darrellwarde

Adds a more step by step guide to Federation. Also adds instructions on how to optimally create a new project.

Fixes some markdown style code blocks.

2023-08-04 12:37 UTC, neo-technology-commit-status-publisher commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-graphql-9.surge.sh
<!-- Sticky Pull Request Commentdocs -->

2023-08-04 13:05 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/create-project.adoc
> += How to create a new project
I believe this is more or less the same that we have in the Getting started, though? I have worked a bit on it in this https://github.com/neo4j/docs-graphql/pull/8PR

2023-08-04 13:46 UTC, lidiazuin requested changes
I'm not sure if we need the create-project.adoc if considered what we have in getting-started/index.adoc. Please check this PR https://github.com/neo4j/docs-graphql/pull/8 to make sure it's the same thing so we can make adjustments . Thanks!

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +[[apollo-federation]]
```suggestion
[[apollo-federation]]
:description: This guide shows how to create a subgraph using the Neo4j GraphQL Library, for composition into a supergraph using Apollo Federation.
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> += How to create a subgraph compatible with Apollo Federation
```suggestion
= Create a subgraph compatible with Apollo Federation
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +This guide shows you how to create a subgraph using the Neo4j GraphQL Library, for composition into a supergraph using Apollo Federation. In this guide, the following monolithic schema will be conver
```suggestion
This guide shows how to create a subgraph using the Neo4j GraphQL Library, for composition into a supergraph using Apollo Federation. 

The objective is to convert the following monolithic schema into a subgraph schema for use behind a Federation gateway:
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +== 1. Create a new project
```suggestion
== Create a new project and install the Apollo Server
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +Follow the steps in xref::how-to-guides/create-project.adoc.
```suggestion
. Follow the steps in xref::how-to-guides/create-project.adoc[How to create a new project].

. Besides the dependencies installed in the previous step, you must install `@apollo/server`, the library for Apollo Server.
It is used in this guide to host the subgraph:

[source, bash]
----
npm install @apollo/server
----
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +== 2. Install dependencies
If you accept the previous suggestion, please delete this section

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +== 3. Opt in to Federation
```suggestion
== Opt in to Federation
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +NOTE: This example only includes the Federation `@key` directive. As you want to use more https://www.apollographql.com/docs/federation/federated-types/federated-directives[Federation directives], yo
```suggestion
Note that this example only includes the Federation `@key` directive. 
To use more https://www.apollographql.com/docs/federation/federated-types/federated-directives[Federation directives], add them to the `import` array.
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +== 4. Define an entity
```suggestion
== Define an entity
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +In order for other subgraphs to be able to contribute fields to the `Movie` type, we must define that type as an https://www.apollographql.com/docs/federation/entities/[entity]. You do this by using
```suggestion
Defining a type as an https://www.apollographql.com/docs/federation/entities/[entity] allows other subgraphs to contribute with fields to the `Movie` type.
To achieve that, use the `@key` directive to designate a field (or fields) as a key:
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +NOTE: Whilst only the `@key` directive has been added in this example, you should consider using either the `@id` or `@unique` directive on the `id` field. The Federation gateway expects each key to
```suggestion
Although only the `@key` directive has been added to this example, consider using either the `@id` or the `@unique` directives on the `id` field.
The Federation gateway expects each key to resolve to one result, so it is good practice to ensure that these values are unique in the database.
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +== 5. Generate a subgraph schema
```suggestion
== Generate a subgraph schema
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +== Complete example
```suggestion
== Conclusion
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/apollo-federation.adoc
> +The above snippets are combined below:
```suggestion
By combining all previous snippets, you should get this:
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/nextjs.adoc
> += How to use the Neo4j GraphQL Library with Next.js
```suggestion
[[next.js]]
:description: This page shows information on how to use the Neo4j GraphQL Library with Next.js
= Use the Neo4j GraphQL Library with Next.js
```

2023-08-04 13:46 UTC, lidiazuin commented on modules/ROOT/pages/how-to-guides/integrations/nextjs.adoc
> +We maintain an https://github.com/vercel/next.js/tree/canary/examples/with-apollo-neo4j-graphql[example project] in the Next.js repository  on how to use the Neo4j GraphQL Library with Next.js.
```suggestion
This https://github.com/vercel/next.js/tree/canary/examples/with-apollo-neo4j-graphql[example project] in the Next.js repository demonstrates how to use Neo4j with https://neo4j.com/docs/getting-started/appendix/example-data/[the "Movies" example], the Neo4j GraphQL Library and https://www.apollographql.com/docs/apollo-server/[Apollo Server].
```

2023-08-04 13:47 UTC, lidiazuin requested changes
I'm not sure if we need the create-project.adoc if considered what we have in getting-started/index.adoc. Please check this PR https://github.com/neo4j/docs-graphql/pull/8 to make sure it's the same thing so we can make adjustments . Thanks!

2023-08-08 12:56 UTC, darrellwarde commented
> I'm not sure if we need the create-project.adoc if considered what we have in getting-started/index.adoc. Please check this PR #8 to make sure it's the same thing so we can make adjustments . Thanks!

My thinking was that creating a project is going to be a fairly common step in many different how-to guides, so we should maybe have a centralised how-to guide on this which all of those other guides can point to.

We can't point to the Getting Started guide because it's a much more holistic example, containing steps further than what most guides will need.

If we repeat ourselves in various different guides, they are not going to get updated so there will be discrepancies across the docs. That was my thinking anyway!

2023-08-30 16:26 UTC, neo-technology-commit-status-publisher commented
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-graphql-9.surge.sh
<!-- Sticky Pull Request Comment -->

2023-08-31 09:37 UTC, lidiazuin approved these changes
LGTM! I only want to make some changes later on when turning some things into lists :) thanks for your work!

2023-08-31 12:35 UTC, merged